---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %> 
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    image_id: 1601
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.4
  driver_plugin: digitalocean
  driver_config:
    image_id: 562354
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: amazon-2013.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-3be4bc52
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: fedora-19
  driver_plugin: digitalocean
  driver_config:
    image_id: 3102879
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: fedora-20
  driver_plugin: digitalocean
  driver_config:
    image_id: 3243145
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

suites:

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  attributes: {}

- name: service_runit
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[chef-client_test::service_runit]
  - recipe[chef-client::runit_service]
  attributes: {}

- name: service_systemd
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::service_systemd]
  - recipe[chef-client::systemd_service]
  excludes: ["centos-5.9", "centos-6.4", "ubuntu-10.04", "ubuntu-12.04"]
  attributes: {}

- name: service_upstart
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::service_upstart]
  - recipe[chef-client::upstart_service]
  excludes: ["centos-5.9"]
  attributes: {}

- name: cron
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::cron]
  attributes: {}

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
  attributes: {}

# Probably needs to be moved up to config and tested there
- name: cook-2092
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2092]
  - recipe[chef-client::config]
  attributes:
    chef_client:
      log_file: "client.log"

# Tests that the "chef server" user is set correctly with the cron recipe.
- name: cook-2169-chef
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2169-chef]
  - recipe[chef-client::cron]
  attributes: {}

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
